export const JSX_ATTRIBUTES = [
  // React-specific
  "className",
  "htmlFor",
  "defaultValue",
  "defaultChecked",
  "onChange",
  "onClick",
  "onBlur",
  "onFocus",
  "onKeyDown",
  "onKeyUp",
  "onMouseEnter",
  "onMouseLeave",
  "onInput",
  "onSubmit",
  "onInvalid",
  "children",
  "key",
  "ref",
  "style",
  "dangerouslySetInnerHTML",
  "suppressContentEditableWarning",
  "suppressHydrationWarning",

  // Accessibility / ARIA
  "role",
  "tabIndex",
  "aria-hidden",
  "aria-label",
  "aria-labelledby",
  "aria-describedby",
  "aria-live",
  "aria-expanded",
  "aria-checked",
  "aria-disabled",
  "aria-required",

  // Data attributes
  "data-testid",
  "data-*",

  // Form/input related
  "name",
  "type",
  "value",
  "placeholder",
  "checked",
  "disabled",
  "readOnly",
  "required",
  "min",
  "max",
  "minLength",
  "maxLength",
  "pattern",
  "step",
  "multiple",
  "accept",
  "autoFocus",
  "autoComplete",
  "autoCorrect",
  "spellCheck",
  "form",
  "formAction",
  "formMethod",
  "formNoValidate",
  "formTarget",
  "inputMode",
  "list",

  // Common HTML attributes
  "id",
  "title",
  "hidden",
  "dir",
  "lang",
  "contentEditable",
  "draggable",
  "accessKey",

  // Media
  "src",
  "alt",
  "width",
  "height",
  "poster",
  "preload",
  "controls",
  "muted",
  "loop",
  "playsInline",

  // Anchor/link
  "href",
  "target",
  "download",
  "rel",

  // Misc
  "dangerouslySetInnerHTML",
  // Add more if needed
] as const;

export const TAG_TO_ELEMENT_TAG: Record<string, keyof HTMLElementTagNameMap> = {
  input: "input",
  textarea: "textarea",
  select: "select",
  button: "button",
  form: "form",
  div: "div",
  span: "span",
  label: "label",
  a: "a",
  img: "img",
  radio: "input",
  checkbox: "input",
  file: "input",
  // Add more if needed
};
